# File: .github/workflows/openshift-build.yml
name: Build & Deploy to OpenShift

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: iamdhikka-dev
  BUILD_NAME: spring-boot-app-build           # BuildConfig di OpenShift
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install oc CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
          tar -xzf openshift-client-linux.tar.gz oc
          sudo mv oc /usr/local/bin/

      - name: Login to OpenShift
        run: |
          oc login --token="$OPENSHIFT_TOKEN" --server="$OPENSHIFT_SERVER"
          oc project "$OPENSHIFT_NAMESPACE"

      - name: Trigger BuildConfig
        run: |
          oc start-build "$BUILD_NAME" --wait --follow
